// Generated by MasonBundleBuilder
import 'package:mason/mason.dart';

final runnerScriptBundle = MasonBundle.fromJson({
  'files': [
    {
      'path': 'runner.dart',
      'data':
          'Ly8vIEdlbmVyYXRlZCBieSBtY3BfZGFydF9jbGkKbGlicmFyeTsKCmltcG9ydCAnZGFydDppbyc7CmltcG9ydCAncGFja2FnZTpsb2dnaW5nL2xvZ2dpbmcuZGFydCcgYXMgbG9nZ2luZzsKaW1wb3J0ICdwYWNrYWdlOm1jcF9kYXJ0L21jcF9kYXJ0LmRhcnQnOwovLyBpZ25vcmU6IHVyaV9kb2VzX25vdF9leGlzdAppbXBvcnQgJ3BhY2thZ2U6e3twYWNrYWdlTmFtZX19L21jcC9tY3AuZGFydCcgYXMgdXNlcl9jb2RlOwppbXBvcnQgJ3BhY2thZ2U6YXJncy9hcmdzLmRhcnQnOwoKdm9pZCBtYWluKExpc3Q8U3RyaW5nPiBhcmdzKSBhc3luYyB7CiAgZmluYWwgcGFyc2VyID0gQXJnUGFyc2VyKCkKICAgIC4uYWRkT3B0aW9uKCd0cmFuc3BvcnQnLCBhbGxvd2VkOiBbJ3N0ZGlvJywgJ2h0dHAnXSwgZGVmYXVsdHNUbzogJ3N0ZGlvJykKICAgIC4uYWRkT3B0aW9uKCdob3N0JywgZGVmYXVsdHNUbzogJzEyNy4wLjAuMScpCiAgICAuLmFkZE9wdGlvbigncG9ydCcsIGRlZmF1bHRzVG86ICczMDAwJyk7CgogIGZpbmFsIHJlc3VsdHMgPSBwYXJzZXIucGFyc2UoYXJncyk7CiAgZmluYWwgdHJhbnNwb3J0ID0gcmVzdWx0c1sndHJhbnNwb3J0J10gYXMgU3RyaW5nOwoKICBpZiAodHJhbnNwb3J0ID09ICdzdGRpbycpIHsKICAgIGZpbmFsIHNlcnZlciA9IHVzZXJfY29kZS5jcmVhdGVNY3BTZXJ2ZXIoKTsKICAgIGZpbmFsIHRyYW5zcG9ydCA9IFN0ZGlvU2VydmVyVHJhbnNwb3J0KCk7CiAgICBhd2FpdCBzZXJ2ZXIuY29ubmVjdCh0cmFuc3BvcnQpOwogIH0gZWxzZSBpZiAodHJhbnNwb3J0ID09ICdodHRwJykgewogICAgdmFyIGhvc3QgPSByZXN1bHRzWydob3N0J10gYXMgU3RyaW5nOwogICAgdmFyIHBvcnQgPSBpbnQucGFyc2UocmVzdWx0c1sncG9ydCddIGFzIFN0cmluZyk7CgogICAgLy8gU2V0dXAgc2ltcGxlIGxvZ2dpbmcgZm9yIEhUVFAKICAgIGxvZ2dpbmcuTG9nZ2VyLnJvb3QubGV2ZWwgPSBsb2dnaW5nLkxldmVsLkFMTDsKICAgIGxvZ2dpbmcuTG9nZ2VyLnJvb3Qub25SZWNvcmQubGlzdGVuKChyZWNvcmQpIHsKICAgICAgc3RkZXJyLndyaXRlbG4oJyR7cmVjb3JkLmxldmVsLm5hbWV9OiAke3JlY29yZC50aW1lfTogJHtyZWNvcmQubWVzc2FnZX0nKTsKICAgIH0pOwogICAgZmluYWwgbG9nZ2VyID0gbG9nZ2luZy5Mb2dnZXIoJ01jcEh0dHBTZXJ2ZXInKTsKCiAgICBmaW5hbCBzZXJ2ZXIgPSBTdHJlYW1hYmxlTWNwU2VydmVyKAogICAgICBzZXJ2ZXJGYWN0b3J5OiAoc2Vzc2lvbklkKSA9PiB1c2VyX2NvZGUuY3JlYXRlTWNwU2VydmVyKCksCiAgICAgIGhvc3Q6IGhvc3QsCiAgICAgIHBvcnQ6IHBvcnQsCiAgICAgIGV2ZW50U3RvcmU6IEluTWVtb3J5RXZlbnRTdG9yZSgpLAogICAgKTsKICAgIGF3YWl0IHNlcnZlci5zdGFydCgpOwogICAgbG9nZ2VyLmluZm8oJ1NlcnZlciBydW5uaW5nIGF0IGh0dHA6Ly8kaG9zdDokcG9ydC9tY3AnKTsKICB9Cn0K',
      'type': 'text',
    },
  ],
  'hooks': [],
  'name': 'runner_script',
  'description': 'A brick to generate the MCP server runner script.',
  'version': '0.1.0',
  'environment': {
    'mason': '>=0.1.0-dev.1 <0.1.0',
  },
  'vars': {
    'packageName': {
      'type': 'string',
      'description': 'The name of the package.',
    },
  },
});
